
local c = require('dracula.palette')

local hl = vim.api.nvim_set_hl
local theme = {}

theme.set_highlights = function()

  -- highlights
  hl(0, "Normal", { fg = c.fg, bg = c.bg })
  hl(0, "SignColumn", { fg = 'NONE', bg = c.bg })
  hl(0, "MsgArea", { fg = c.fg, bg = c.bg })
  hl(0, "ModeMsg", { fg = c.fg, bg = c.black })
  hl(0, "MsgSeparator", { fg = c.fg, bg = c.bg })
  hl(0, "SpellBad", { fg = c.bright_red, bg = 'NONE', underline=true, })
  hl(0, "SpellCap", { fg = c.yellow, bg = 'NONE', underline=true, })
  hl(0, "SpellLocal", { fg = c.yellow, bg = 'NONE', underline=true, })
  hl(0, "SpellRare", { fg = c.yellow, bg = 'NONE', underline=true, })
  hl(0, "NormalNC", { fg = c.fg, bg = c.bg })
  hl(0, "Pmenu", { fg = c.purple, bg = c.menu, sp = 'NONE', blend=50,  })
  hl(0, "PmenuSel", { fg = c.white, bg = c.selection })
  hl(0, "WildMenu", { fg = c.black, bg = c.white })
  hl(0, "CursorLineNr", { fg = c.fg, bg = 'NONE', bold=true, })
  hl(0, "Comment", { fg = c.comment, bg = 'NONE', italic=true, })
  hl(0, "Folded", { fg = c.comment, bg = 'NONE' })
  hl(0, "FoldColumn", { fg = c.white, bg = c.black })
  hl(0, "LineNr", { fg = c.comment, bg = 'NONE' })
  hl(0, "FloatBoder", { fg = c.white, bg = c.black })
  hl(0, "Whitespace", { fg = c.bg, bg = 'NONE' })
  hl(0, "VertSplit", { fg = c.white, bg = c.bg })
  hl(0, "CursorLine", { fg = 'NONE', bg = c.selection })
  hl(0, "CursorColumn", { fg = 'NONE', bg = c.black })
  hl(0, "ColorColumn", { fg = 'NONE', bg = c.selection })
  hl(0, "NormalFloat", { fg = 'NONE', bg = c.bg })
  hl(0, "Visual", { fg = 'NONE', bg = c.accent })
  hl(0, "VisualNOS", { fg = c.accent, bg = 'NONE' })
  hl(0, "WarningMsg", { fg = c.yellow, bg = 'NONE' })
  hl(0, "DiffAdd", { fg = c.bg, bg = c.green })
  hl(0, "DiffChange", { fg = c.orange, bg = 'NONE', underline=true, })
  hl(0, "DiffDelete", { fg = c.red, bg = 'NONE' })
  hl(0, "DiffText", { fg = c.comment, bg = 'NONE' })
  hl(0, "QuickFixLine", { fg = c.black, bg = c.yellow })
  hl(0, "PmenuSbar", { fg = 'NONE', bg = c.bg })
  hl(0, "PmenuThumb", { fg = 'NONE', bg = c.selection })
  hl(0, "MatchWord", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "MatchParen", { fg = c.bright_cyan, bg = c.bg, underline=true, })
  hl(0, "MatchWordCur", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "MatchParenCur", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "Cursor", { fg = c.fg, bg = c.bg })
  hl(0, "lCursor", { fg = c.fg, bg = c.bg })
  hl(0, "CursorIM", { fg = c.fg, bg = c.bg })
  hl(0, "TermCursor", { fg = c.fg, bg = c.bg_lighter })
  hl(0, "TermCursorNC", { fg = c.fg, bg = c.bg_lighter })
  hl(0, "Conceal", { fg = c.comment, bg = 'NONE' })
  hl(0, "Directory", { fg = c.cyan, bg = 'NONE' })
  hl(0, "SpecialKey", { fg = c.cyan, bg = 'NONE', bold=true, })
  hl(0, "Title", { fg = c.cyan, bg = 'NONE', bold=true, })
  hl(0, "ErrorMsg", { fg = c.bright_red, bg = c.bg, bold=true, })
  hl(0, "Search", { fg = c.black, bg = c.orange })
  hl(0, "IncSearch", { fg = c.orange, bg = c.comment })
  hl(0, "Substitute", { fg = c.white, bg = c.orange })
  hl(0, "MoreMsg", { fg = c.orange, bg = 'NONE' })
  hl(0, "Question", { fg = c.purple, bg = 'NONE' })
  hl(0, "EndOfBuffer", { fg = c.bg, bg = 'NONE' })
  hl(0, "NonText", { fg = c.bg, bg = 'NONE' })
  hl(0, "Variable", { fg = c.bright_cyan, bg = 'NONE' })
  hl(0, "String", { fg = c.yellow, bg = 'NONE' })
  hl(0, "Character", { fg = c.green, bg = 'NONE' })
  hl(0, "Constant", { fg = c.yellow, bg = 'NONE' })
  hl(0, "Number", { fg = c.orange, bg = 'NONE' })
  hl(0, "Boolean", { fg = c.cyan, bg = 'NONE' })
  hl(0, "Float", { fg = c.orange, bg = 'NONE' })
  hl(0, "FloatBorder", { fg = c.white, bg = 'NONE' })
  hl(0, "Identifier", { fg = c.cyan, bg = 'NONE' })
  hl(0, "Function", { fg = c.yellow, bg = 'NONE' })
  hl(0, "Operator", { fg = c.purple, bg = 'NONE' })
  hl(0, "Type", { fg = c.cyan, bg = 'NONE' })
  hl(0, "StorageClass", { fg = c.pink, bg = 'NONE' })
  hl(0, "Structure", { fg = c.yellow, bg = 'NONE' })
  hl(0, "Typedef", { fg = c.yellow, bg = 'NONE' })
  hl(0, "Keyword", { fg = c.cyan, bg = 'NONE' })
  hl(0, "Keywords", { fg = c.cyan, bg = 'NONE' })
  hl(0, "Statement", { fg = c.purple, bg = 'NONE' })
  hl(0, "Conditional", { fg = c.pink, bg = 'NONE' })
  hl(0, "Repeat", { fg = c.pink, bg = 'NONE' })
  hl(0, "Label", { fg = c.cyan, bg = 'NONE' })
  hl(0, "Exception", { fg = c.purple, bg = 'NONE' })
  hl(0, "Include", { fg = c.purple, bg = 'NONE' })
  hl(0, "PreProc", { fg = c.yellow, bg = 'NONE' })
  hl(0, "Define", { fg = c.purple, bg = 'NONE' })
  hl(0, "Macro", { fg = c.purple, bg = 'NONE' })
  hl(0, "PreCondit", { fg = c.cyan, bg = 'NONE' })
  hl(0, "Special", { fg = c.green, bg = 'NONE' })
  hl(0, "SpecialChar", { fg = c.yellow, bg = 'NONE' })
  hl(0, "Tag", { fg = c.cyan, bg = 'NONE' })
  hl(0, "Debug", { fg = c.red, bg = 'NONE' })
  hl(0, "Delimiter", { fg = c.white, bg = 'NONE' })
  hl(0, "SpecialComment", { fg = c.comment, bg = 'NONE' })
  hl(0, "Underlined", { fg = c.cyan, bg = 'NONE', underline=true, })
  hl(0, "Bold", { fg = 'NONE', bg = 'NONE', bold=true, })
  hl(0, "Italic", { fg = 'NONE', bg = 'NONE', italic=true, })
  hl(0, "Ignore", { fg = c.cyan, bg = c.bg, bold=true, })
  hl(0, "Todo", { fg = c.purple, bg = c.bg, bold=true, })
  hl(0, "Error", { fg = c.bright_red, bg = c.bg, bold=true, })
  hl(0, "TabLine", { fg = c.fg, bg = c.bg_dark })
  hl(0, "TabLineSel", { fg = c.fg, bg = 'NONE' })
  hl(0, "TabLineFill", { fg = 'NONE', bg = c.bg_dark })

  -- Treesitter
  hl(0, "TSComment", { link = 'Comment' })
  hl(0, "TSAnnotation", { fg = c.yellow, bg = 'NONE' })
  hl(0, "TSAttribute", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSConstructor", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSType", { fg = c.bright_cyan, bg = 'NONE' })
  hl(0, "TSTypeBuiltin", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSConditional", { fg = c.pink, bg = 'NONE' })
  hl(0, "TSException", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSInclude", { fg = c.pink, bg = 'NONE' })
  hl(0, "TSKeywordReturn", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSKeyword", { fg = c.pink, bg = 'NONE' })
  hl(0, "TSKeywordFunction", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSLabel", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSNamespace", { fg = c.orange, bg = 'NONE' })
  hl(0, "TSRepeat", { fg = c.pink, bg = 'NONE' })
  hl(0, "TSConstant", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSConstBuiltin", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSConstantBuiltin", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSFloat", { fg = c.green, bg = 'NONE' })
  hl(0, "TSNumber", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSBoolean", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSCharacter", { fg = c.green, bg = 'NONE' })
  hl(0, "TSError", { fg = c.red, bg = 'NONE' })
  hl(0, "TSFunction", { fg = c.green, bg = 'NONE' })
  hl(0, "TSFuncBuiltin", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSMethod", { fg = c.green, bg = 'NONE' })
  hl(0, "TSConstMacro", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSFuncMacro", { fg = c.green, bg = 'NONE' })
  hl(0, "TSVariable", { fg = c.fg, bg = 'NONE' })
  hl(0, "TSVariableBuiltin", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSProperty", { fg = c.fg, bg = 'NONE' })
  hl(0, "TSField", { fg = c.orange, bg = 'NONE' })
  hl(0, "TSParameter", { fg = c.orange, bg = 'NONE' })
  hl(0, "TSParameterReference", { fg = c.orange, bg = 'NONE' })
  hl(0, "TSSymbol", { fg = c.bright_cyan, bg = 'NONE' })
  hl(0, "TSText", { fg = c.orange, bg = 'NONE' })
  hl(0, "TSOperator", { fg = c.pink, bg = 'NONE' })
  hl(0, "TSPunctDelimiter", { fg = c.fg, bg = 'NONE' })
  hl(0, "TSTagDelimiter", { fg = c.white, bg = 'NONE' })
  hl(0, "TSTagAttribute", { fg = c.orange, bg = 'NONE' })
  hl(0, "TSPunctBracket", { fg = c.fg, bg = 'NONE' })
  hl(0, "TSPunctSpecial", { fg = c.fg, bg = 'NONE' })
  hl(0, "TSString", { fg = c.yellow, bg = 'NONE' })
  hl(0, "TSStringRegex", { fg = c.red, bg = 'NONE' })
  hl(0, "TSStringEscape", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSTag", { fg = c.cyan, bg = 'NONE' })
  hl(0, "TSEmphasis", { fg = c.yellow, bg = 'NONE', italic=true, })
  hl(0, "TSUnderline", { fg = c.orange, bg = 'NONE', underline=true, })
  hl(0, "TSTitle", { fg = c.pink, bg = 'NONE',  })
  hl(0, "TSLiteral", { fg = c.yellow, bg = 'NONE' })
  hl(0, "TSURI", { fg = c.yellow, bg = 'NONE', italic=true, })
  hl(0, "TSKeywordOperator", { fg = c.pink, bg = 'NONE' })
  hl(0, "TSStructure", { fg = c.purple, bg = 'NONE' })
  hl(0, "TSStrong", { fg = c.orange, bg = 'NONE', bold=true, })
  hl(0, "TSQueryLinterError", { fg = c.orange, bg = 'NONE' })
  hl(0, "TreesitterContext", { fg = 'NONE', bg = c.white })

  -- markdown
  hl(0, "markdownBlockquote", { fg = c.yellow, bg = 'NONE' })
  hl(0, "markdownCode", { fg = c.green, bg = 'NONE' })
  hl(0, "markdownCodeBlock", { fg = c.orange, bg = 'NONE' })
  hl(0, "markdownCodeDelimiter", { fg = c.red, bg = 'NONE' })
  hl(0, "markdownH1", { fg = c.pink, bg = 'NONE', bold=true, })
  hl(0, "markdownH2", { fg = c.pink, bg = 'NONE', bold=true, })
  hl(0, "markdownH3", { fg = c.pink, bg = 'NONE', bold=true, })
  hl(0, "markdownH4", { fg = c.pink, bg = 'NONE', bold=true, })
  hl(0, "markdownH5", { fg = c.pink, bg = 'NONE', bold=true, })
  hl(0, "markdownH6", { fg = c.pink, bg = 'NONE', bold=true, })
  hl(0, "markdownHeadingDelimiter", { fg = c.red, bg = 'NONE' })
  hl(0, "markdownHeadingRule", { fg = c.comment, bg = 'NONE' })
  hl(0, "markdownId", { fg = c.purple, bg = 'NONE' })
  hl(0, "markdownIdDeclaration", { fg = c.cyan, bg = 'NONE' })
  hl(0, "markdownIdDelimiter", { fg = c.purple, bg = 'NONE' })
  hl(0, "markdownLinkDelimiter", { fg = c.purple, bg = 'NONE' })
  hl(0, "markdownBold", { fg = c.orange, bg = 'NONE', bold=true, })
  hl(0, "markdownItalic", { fg = c.yellow, bg = 'NONE', italic=true, })
  hl(0, "markdownBoldItalic", { fg = c.yellow, bg = 'NONE', bold=true, italic=true, })
  hl(0, "markdownListMarker", { fg = c.cyan, bg = 'NONE' })
  hl(0, "markdownOrderedListMarker", { fg = c.red, bg = 'NONE' })
  hl(0, "markdownRule", { fg = c.comment, bg = 'NONE' })
  hl(0, "markdownUrl", { fg = c.cyan, bg = 'NONE', underline=true, })
  hl(0, "markdownLinkText", { fg = c.pink, bg = 'NONE' })
  hl(0, "markdownFootnote", { fg = c.orange, bg = 'NONE' })
  hl(0, "markdownFootnoteDefinition", { fg = c.orange, bg = 'NONE' })
  hl(0, "markdownEscape", { fg = c.yellow, bg = 'NONE' })

  -- Whichkey
  hl(0, "WhichKey", { fg = c.pink, bg = 'NONE' })
  hl(0, "WhichKeySeperator", { fg = c.green, bg = 'NONE' })
  hl(0, "WhichKeyGroup", { fg = c.cyan, bg = 'NONE' })
  hl(0, "WhichKeyDesc", { fg = c.bright_blue, bg = 'NONE' })
  hl(0, "WhichKeyFloat", { fg = 'NONE', bg = c.bg })

  -- Git
  hl(0, "SignAdd", { fg = c.bright_green, bg = 'NONE' })
  hl(0, "SignChange", { fg = c.cyan, bg = 'NONE' })
  hl(0, "SignDelete", { fg = c.bright_red, bg = 'NONE' })
  hl(0, "GitSignsAdd", { fg = c.bright_green, bg = 'NONE' })
  hl(0, "GitSignsChange", { fg = c.cyan, bg = 'NONE' })
  hl(0, "GitSignsDelete", { fg = c.bright_red, bg = 'NONE' })

  -- LSP
  hl(0, "LspDiagnosticsDefaultError", { fg = c.red, bg = 'NONE' })
  hl(0, "LspDiagnosticsDefaultWarning", { fg = c.yellow, bg = 'NONE' })
  hl(0, "LspDiagnosticsDefaultInformation", { fg = c.cyan, bg = 'NONE' })
  hl(0, "LspDiagnosticsDefaultInfo", { fg = c.cyan, bg = 'NONE' })
  hl(0, "LspDiagnosticsDefaultHint", { fg = c.cyan, bg = 'NONE' })
  hl(0, "LspDiagnosticsVirtualTextError", { fg = c.red, bg = 'NONE' })
  hl(0, "LspDiagnosticsVirtualTextWarning", { fg = c.yellow, bg = 'NONE' })
  hl(0, "LspDiagnosticsVirtualTextInformation", { fg = c.cyan, bg = 'NONE' })
  hl(0, "LspDiagnosticsVirtualTextInfo", { fg = c.cyan, bg = 'NONE' })
  hl(0, "LspDiagnosticsVirtualTextHint", { fg = c.cyan, bg = 'NONE' })
  hl(0, "LspDiagnosticsFloatingError", { fg = c.red, bg = 'NONE' })
  hl(0, "LspDiagnosticsFloatingWarning", { fg = c.yellow, bg = 'NONE' })
  hl(0, "LspDiagnosticsFloatingInformation", { fg = c.cyan, bg = 'NONE' })
  hl(0, "LspDiagnosticsFloatingInfo", { fg = c.cyan, bg = 'NONE' })
  hl(0, "LspDiagnosticsFloatingHint", { fg = c.cyan, bg = 'NONE' })
  hl(0, "DiagnosticSignError", { fg = c.red, bg = 'NONE' })
  hl(0, "DiagnosticSignWarning", { fg = c.yellow, bg = 'NONE' })
  hl(0, "DiagnosticSignInformation", { fg = c.cyan, bg = 'NONE' })
  hl(0, "DiagnosticSignInfo", { fg = c.cyan, bg = 'NONE' })
  hl(0, "DiagnosticSignHint", { fg = c.cyan, bg = 'NONE' })
  hl(0, "LspDiagnosticsSignError", { fg = c.red, bg = 'NONE' })
  hl(0, "LspDiagnosticsSignWarning", { fg = c.yellow, bg = 'NONE' })
  hl(0, "LspDiagnosticsSignInformation", { fg = c.cyan, bg = 'NONE' })
  hl(0, "LspDiagnosticsSignInfo", { fg = c.cyan, bg = 'NONE' })
  hl(0, "LspDiagnosticsSignHint", { fg = c.cyan, bg = 'NONE' })
  hl(0, "LspDiagnosticsError", { fg = c.red, bg = 'NONE' })
  hl(0, "LspDiagnosticsWarning", { fg = c.yellow, bg = 'NONE' })
  hl(0, "LspDiagnosticsInformation", { fg = c.cyan, bg = 'NONE' })
  hl(0, "LspDiagnosticsInfo", { fg = c.cyan, bg = 'NONE' })
  hl(0, "LspDiagnosticsHint", { fg = c.cyan, bg = 'NONE' })
  hl(0, "LspDiagnosticsUnderlineError", { fg = 'NONE', bg = 'NONE', sp = c.red, underline=true, })
  hl(0, "LspDiagnosticsUnderlineWarning", { fg = 'NONE', bg = 'NONE', sp = c.yellow, underline=true, })
  hl(0, "LspDiagnosticsUnderlineInformation", { fg = 'NONE', bg = 'NONE', sp = c.cyan, underline=true, })
  hl(0, "LspDiagnosticsUnderlineInfo", { fg = 'NONE', bg = 'NONE', sp = c.cyan, underline=true, })
  hl(0, "LspDiagnosticsUnderlineHint", { fg = 'NONE', bg = 'NONE', sp = c.cyan, underline=true, })
  hl(0, "LspReferenceRead", { fg = c.orange, bg = 'NONE' })
  hl(0, "LspReferenceText", { fg = c.orange, bg = 'NONE' })
  hl(0, "LspReferenceWrite", { fg = c.orange, bg = 'NONE' })
  hl(0, "LspCodeLens", { fg = c.context, bg = 'NONE', italic=true, })
  hl(0, "LspCodeLensSeparator", { fg = c.context, bg = 'NONE', italic=true, })

  -- Telescope
  hl(0, "TelescopeSelection", { fg = c.white, bg = c.selection })
  hl(0, "TelescopeMultiSelection", { fg = c.purple, bg = c.selection })
  hl(0, "TelescopeNormal", { fg = c.fg, bg = c.bg })
  hl(0, "TelescopeMatching", { fg = c.green, bg = 'NONE' })
  hl(0, "TelescopeBorder", { fg = c.comment, bg = 'NONE' })
  hl(0, "TelescopePromptPrefix", { fg = c.purple, bg = 'NONE' })

  -- NvimTree
  hl(0, "NvimTreeFolderIcon", { fg = c.purple, bg = 'NONE' })
  hl(0, "NvimTreeIndentMarker", { fg = c.white, bg = 'NONE' })
  hl(0, "NvimTreeNormal", { fg = c.white, bg = c.bg_dark })
  hl(0, "NvimTreeNormalNC", { link = 'NvimTreeNormal' })
  hl(0, "NvimTreeVertSplit", { fg = c.bg_dark, bg = c.bg })
  hl(0, "NvimTreeFolderName", { fg = c.fg, bg = 'NONE' })
  hl(0, "NvimTreeOpenedFolderName", { fg = c.fg, bg = 'NONE', bold=true, italic=true, })
  hl(0, "NvimTreeEmptyFolderName", { fg = c.comment, bg = 'NONE', italic=true, })
  hl(0, "NvimTreeGitIgnored", { fg = c.white, bg = 'NONE', italic=true, })
  hl(0, "NvimTreeImageFile", { fg = c.pink, bg = 'NONE' })
  hl(0, "NvimTreeSpecialFile", { fg = c.pink, bg = 'NONE' })
  hl(0, "NvimTreeEndOfBuffer", { fg = c.white, bg = 'NONE' })
  hl(0, "NvimTreeCursorLine", { fg = 'NONE', bg = c.selection })
  hl(0, "NvimTreeGitignoreIcon", { fg = c.orange, bg = 'NONE' })
  hl(0, "NvimTreeGitStaged", { fg = c.cyan, bg = 'NONE' })
  hl(0, "NvimTreeGitNew", { fg = c.bright_green, bg = 'NONE' })
  hl(0, "NvimTreeGitRenamed", { fg = c.green, bg = 'NONE' })
  hl(0, "NvimTreeGitDeleted", { fg = c.red, bg = 'NONE' })
  hl(0, "NvimTreeGitMerge", { fg = c.cyan, bg = 'NONE' })
  hl(0, "NvimTreeGitDirty", { fg = c.yellow, bg = 'NONE' })
  hl(0, "NvimTreeSymlink", { fg = c.orange, bg = 'NONE' })
  hl(0, "NvimTreeRootFolder", { fg = c.fg, bg = 'NONE', bold=true, })
  hl(0, "NvimTreeExecFile", { fg = c.bright_green, bg = 'NONE' })

  -- Buffer
  hl(0, "BufferCurrent", { fg = c.fg, bg = c.bg })
  hl(0, "BufferCurrentIndex", { fg = c.fg, bg = c.bg })
  hl(0, "BufferCurrentMod", { fg = c.yellow, bg = c.bg })
  hl(0, "BufferCurrentSign", { fg = c.bright_cyan, bg = c.bg })
  hl(0, "BufferCurrentTarget", { fg = c.red, bg = c.bg, bold=true, })
  hl(0, "BufferVisible", { fg = c.fg, bg = c.bg })
  hl(0, "BufferVisibleIndex", { fg = c.fg, bg = c.bg })
  hl(0, "BufferVisibleMod", { fg = c.yellow, bg = c.bg })
  hl(0, "BufferVisibleSign", { fg = c.white, bg = c.bg })
  hl(0, "BufferVisibleTarget", { fg = c.red, bg = c.bg, bold=true, })
  hl(0, "BufferInactive", { fg = c.white, bg = c.black })
  hl(0, "BufferInactiveIndex", { fg = c.white, bg = c.black })
  hl(0, "BufferInactiveMod", { fg = c.yellow, bg = c.black })
  hl(0, "BufferInactiveSign", { fg = c.white, bg = c.black })
  hl(0, "BufferInactiveTarget", { fg = c.red, bg = c.black, bold=true, })

  -- StatusLine
  hl(0, "StatusLine", { fg = c.white, bg = c.bg_dark })
  hl(0, "StatusLineNC", { fg = c.comment, bg = 'NONE' })
  hl(0, "StatusLineSeparator", { fg = c.bg_dark, bg = 'NONE' })
  hl(0, "StatusLineTerm", { fg = c.white, bg = c.black })
  hl(0, "StatusLineTermNC", { fg = c.comment, bg = 'NONE' })

  -- IndentBlankline
  hl(0, "IndentBlanklineContextChar", { fg = c.context, bg = 'NONE' })
  hl(0, "IndentBlanklineContextStart", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "IndentBlanklineChar", { fg = c.white, bg = 'NONE' })
  hl(0, "IndentBlanklineSpaceChar", { fg = c.cyan, bg = 'NONE' })
  hl(0, "IndentBlanklineSpaceCharBlankline", { fg = c.yellow, bg = 'NONE' })

  -- Dashboard
  hl(0, "DashboardHeader", { fg = c.purple, bg = 'NONE' })
  hl(0, "DashboardCenter", { fg = c.pink, bg = 'NONE' })
  hl(0, "DashboardFooter", { fg = c.purple, bg = 'NONE' })

  -- Cmp
  hl(0, "CmpItemAbbrDeprecated", { fg = c.white, bg = c.menu, strikethrough=true, })
  hl(0, "CmpItemAbbrMatch", { fg = c.cyan, bg = c.menu })
  hl(0, "CmpItemAbbrMatchFuzzy", { fg = c.cyan, bg = c.menu })
  hl(0, "CmpItemKindFunction", { link = 'TSFunction' })
  hl(0, "CmpItemKindMethod", { link = 'TSMethod' })
  hl(0, "CmpItemKindConstructor", { link = 'TSConstructor' })
  hl(0, "CmpItemKindClass", { link = 'TSType' })
  hl(0, "CmpItemKindEnum", { link = 'TSField' })
  hl(0, "CmpItemKindEvent", { link = 'TSConstant' })
  hl(0, "CmpItemKindInterface", { link = 'TSType' })
  hl(0, "CmpItemKindStruct", { link = 'TSStructure' })
  hl(0, "CmpItemKindVariable", { link = 'TSVariable' })
  hl(0, "CmpItemKindField", { link = 'TSField' })
  hl(0, "CmpItemKindProperty", { link = 'TSProperty' })
  hl(0, "CmpItemKindEnumMember", { link = 'TSField' })
  hl(0, "CmpItemKindConstant", { link = 'TSConstant' })
  hl(0, "CmpItemKindKeyword", { link = 'TSKeyword' })
  hl(0, "CmpItemKindModule", { link = 'TSNamespace' })
  hl(0, "CmpItemKindValue", { link = 'TSField' })
  hl(0, "CmpItemKindUnit", { link = 'TSField' })
  hl(0, "CmpItemKindText", { link = 'TSText' })
  hl(0, "CmpItemKindSnippet", { link = 'TSText' })
  hl(0, "CmpItemKindFile", { link = 'TSURI' })
  hl(0, "CmpItemKindFolder", { link = 'TSURI' })
  hl(0, "CmpItemKindColor", { fg = c.fg, bg = 'NONE' })
  hl(0, "CmpItemKindReference", { link = 'TSParameterReference' })
  hl(0, "CmpItemKindOperator", { link = 'TSOperator' })
  hl(0, "CmpItemKindTypeParameter", { link = 'TSParameter' })

  -- Notify
  hl(0, "NotifyERRORBorder", { fg = c.red, bg = 'NONE' })
  hl(0, "NotifyWARNBorder", { fg = c.yellow, bg = 'NONE' })
  hl(0, "NotifyINFOBorder", { fg = c.cyan, bg = 'NONE' })
  hl(0, "NotifyDEBUGBorder", { fg = c.red, bg = 'NONE' })
  hl(0, "NotifyTRACEBorder", { fg = c.white, bg = 'NONE' })
  hl(0, "NotifyERRORIcon", { fg = c.red, bg = 'NONE' })
  hl(0, "NotifyWARNIcon", { fg = c.yellow, bg = 'NONE' })
  hl(0, "NotifyINFOIcon", { fg = c.cyan, bg = 'NONE' })
  hl(0, "NotifyDEBUGIcon", { fg = c.white, bg = 'NONE' })
  hl(0, "NotifyTRACEIcon", { fg = c.white, bg = 'NONE' })
  hl(0, "NotifyERRORTitle", { fg = c.red, bg = 'NONE' })
  hl(0, "NotifyWARNTitle", { fg = c.yellow, bg = 'NONE' })
  hl(0, "NotifyINFOTitle", { fg = c.cyan, bg = 'NONE' })
  hl(0, "NotifyDEBUGTitle", { fg = c.white, bg = 'NONE' })
  hl(0, "NotifyTRACETitle", { fg = c.white, bg = 'NONE' })
  hl(0, "NotifyERRORBody", { link = 'Normal' })
  hl(0, "NotifyWARNBody", { link = 'Normal' })
  hl(0, "NotifyINFOBody", { link = 'Normal' })
  hl(0, "NotifyDEBUGBody", { link = 'Normal' })
  hl(0, "NotifyTRACEBody", { link = 'Normal' })
end

return theme