[information]
name = "dracula"
background = "dark"
author = "Jose Tiburcio Ribeiro Netto <jnetto@mineiro.org>"

[palette]
bg = '#22212C'
bg_dark = "#17161D"
bg_darker = "#0B0B0F"
bg_light = "#2E2B3B"
bg_lighter = "#393649"
fg = '#F8F8F2'
white = '#ABB2BF'
black = "#191A21"
green = '#50FA7B'
cyan = '#8BE9FD'
red = '#FF5555'
orange = '#FFB86C'
yellow = '#F1FA8C'
purple = '#BD93F9'
pink = "#FF79C6"

bright_red = "#FF6E6E"
bright_green = "#69FF94"
bright_yellow = "#FFFFA5"
bright_blue = "#D6ACFF"
bright_magenta = "#FF92DF"
bright_cyan = "#A4FFFF"
bright_white = "#FFFFFF"

selection = "#454158"
context = "#44475A"
comment = "#7970A9"
subtle = "#424450"

menu = "#21222C"
accent = "#3E4452"
gutter_fg = "#4B5263"
nontext = "#3B4048"

[highlights]
Normal = 'fg bg'
SignColumn = '- bg'
MsgArea = 'fg bg'
ModeMsg = 'fg black'
MsgSeparator = 'fg bg'
SpellBad = 'bright_red - u'
SpellCap = 'yellow - u'
SpellLocal = 'yellow - u'
SpellRare = 'yellow - u'
NormalNC = 'fg bg'
Pmenu = 'purple menu - - 50'
PmenuSel = 'white selection'
WildMenu = 'black white'
CursorLineNr = 'fg - b'
Comment = 'comment - i'
Folded = 'comment'
FoldColumn = 'white black'
LineNr = 'comment'
FloatBoder = 'white black'
Whitespace = 'bg -'
VertSplit = 'white bg'
CursorLine = '- selection'
CursorColumn = '- black'
ColorColumn = '- selection'
NormalFloat = '- bg'
Visual = '- accent'
VisualNOS = 'accent -'
WarningMsg = 'yellow'
DiffAdd = 'bg green'
DiffChange = 'orange - u'
DiffDelete = 'red'
DiffText = 'comment'
QuickFixLine = 'black yellow'
PmenuSbar = '- bg'
PmenuThumb = '- selection'
MatchWord = '- - u'
MatchParen = 'bright_cyan bg u'
MatchWordCur = '- - u'
MatchParenCur = '- - u'
Cursor = 'fg bg'
lCursor = 'fg bg'
CursorIM = 'fg bg'
TermCursor = 'fg bg_lighter'
TermCursorNC = 'fg bg_lighter'
Conceal = 'comment'
Directory = 'cyan'
SpecialKey = 'cyan - b'
Title = 'cyan - b'
ErrorMsg = 'bright_red bg b'
Search = 'black orange'
IncSearch = 'orange comment'
Substitute = 'white orange'
MoreMsg = 'orange'
Question = 'purple'
EndOfBuffer = 'bg'
NonText = 'bg'
Variable = 'bright_cyan'
String = 'yellow'
Character = 'green'
Constant = 'yellow'
Number = 'orange'
Boolean = 'cyan'
Float = 'orange'
FloatBorder = 'white'
Identifier = 'cyan'
Function = 'yellow'
Operator = 'purple'
Type = 'cyan'
StorageClass = 'pink'
Structure = 'yellow'
Typedef = 'yellow'
Keyword = 'cyan'
Keywords = 'cyan'
Statement = 'purple'
Conditional = 'pink'
Repeat = 'pink'
Label = 'cyan'
Exception = 'purple'
Include = 'purple'
PreProc = 'yellow'
Define = 'purple'
Macro = 'purple'
PreCondit = 'cyan'
Special = 'green'
SpecialChar = 'yellow'
Tag = 'cyan'
Debug = 'red'
Delimiter = 'white -'
SpecialComment = 'comment'
Underlined = 'cyan - u'
Bold = '- - b'
Italic = '- - i'
Ignore = 'cyan bg b'
Todo = 'purple bg b'
Error = 'bright_red bg b'
TabLine = 'fg bg_dark'
TabLineSel = 'fg'
TabLineFill = '- bg_dark'

[Treesitter]
TSComment = 'link:Comment'
TSAnnotation = 'yellow'
TSAttribute = 'cyan'
TSConstructor = 'cyan'
TSType = 'bright_cyan'
TSTypeBuiltin = 'cyan'
TSConditional = 'pink'
TSException = 'purple'
TSInclude = 'pink'
TSKeywordReturn = 'purple'
TSKeyword = 'pink'
TSKeywordFunction = 'cyan'
TSLabel = 'cyan'
TSNamespace = 'orange'
TSRepeat = 'pink'
TSConstant = 'purple'
TSConstBuiltin = 'purple'
TSConstantBuiltin = 'purple'
TSFloat = 'green'
TSNumber = 'purple'
TSBoolean = 'purple'
TSCharacter = 'green'
TSError = 'red'
TSFunction = 'green'
TSFuncBuiltin = 'cyan'
TSMethod = 'green'
TSConstMacro = 'cyan'
TSFuncMacro = 'green'
TSVariable = 'fg'
TSVariableBuiltin = 'purple'
TSProperty = 'fg'
TSField = 'orange'
TSParameter = 'orange'
TSParameterReference = 'orange'
TSSymbol = 'bright_cyan'
TSText = 'orange'
TSOperator = 'pink'
TSPunctDelimiter = 'fg -'
TSTagDelimiter = 'white'
TSTagAttribute = 'orange'
TSPunctBracket = 'fg -'
TSPunctSpecial = 'fg -'
TSString = 'yellow'
TSStringRegex = 'red'
TSStringEscape = 'cyan'
TSTag = 'cyan'
TSEmphasis = 'yellow - i'
TSUnderline = 'orange - u'
TSTitle = 'pink - -'
TSLiteral = 'yellow'
TSURI = 'yellow - i'
TSKeywordOperator = 'pink'
TSStructure = 'purple'
TSStrong = 'orange - b'
TSQueryLinterError = 'orange'
TreesitterContext = '- white'

[markdown]
markdownBlockquote = 'yellow'
markdownCode = 'green'
markdownCodeBlock = 'orange'
markdownCodeDelimiter = 'red'
markdownH1 = 'pink - b'
markdownH2 = 'pink - b'
markdownH3 = 'pink - b'
markdownH4 = 'pink - b'
markdownH5 = 'pink - b'
markdownH6 = 'pink - b'
markdownHeadingDelimiter = 'red'
markdownHeadingRule = 'comment'
markdownId = 'purple'
markdownIdDeclaration = 'cyan'
markdownIdDelimiter = 'purple'
markdownLinkDelimiter = 'purple'
markdownBold = 'orange - b'
markdownItalic = 'yellow - i'
markdownBoldItalic = 'yellow - bi'
markdownListMarker = 'cyan'
markdownOrderedListMarker = 'red'
markdownRule = 'comment'
markdownUrl = 'cyan - u'
markdownLinkText = 'pink'
markdownFootnote = 'orange'
markdownFootnoteDefinition = 'orange'
markdownEscape = 'yellow'

# [toml]
# tomlTSPunctBracket = 'yellow'
# tomlTSProperty = 'pink'
# tomlTSPunctDelimiter = 'green'

[Whichkey]
WhichKey = 'pink'
WhichKeySeperator = 'green'
WhichKeyGroup = 'cyan'
WhichKeyDesc = 'bright_blue'
WhichKeyFloat = '- bg'

[Git]
SignAdd = 'bright_green'
SignChange = 'cyan'
SignDelete = 'bright_red'
GitSignsAdd = 'bright_green'
GitSignsChange = 'cyan'
GitSignsDelete = 'bright_red'

[LSP]
LspDiagnosticsDefaultError = 'red'
LspDiagnosticsDefaultWarning = 'yellow'
LspDiagnosticsDefaultInformation = 'cyan'
LspDiagnosticsDefaultInfo = 'cyan'
LspDiagnosticsDefaultHint = 'cyan'
LspDiagnosticsVirtualTextError = 'red'
LspDiagnosticsVirtualTextWarning = 'yellow'
LspDiagnosticsVirtualTextInformation = 'cyan'
LspDiagnosticsVirtualTextInfo = 'cyan'
LspDiagnosticsVirtualTextHint = 'cyan'
LspDiagnosticsFloatingError = 'red'
LspDiagnosticsFloatingWarning = 'yellow'
LspDiagnosticsFloatingInformation = 'cyan'
LspDiagnosticsFloatingInfo = 'cyan'
LspDiagnosticsFloatingHint = 'cyan'
DiagnosticSignError = 'red'
DiagnosticSignWarning = 'yellow'
DiagnosticSignInformation = 'cyan'
DiagnosticSignInfo = 'cyan'
DiagnosticSignHint = 'cyan'
LspDiagnosticsSignError = 'red'
LspDiagnosticsSignWarning = 'yellow'
LspDiagnosticsSignInformation = 'cyan'
LspDiagnosticsSignInfo = 'cyan'
LspDiagnosticsSignHint = 'cyan'
LspDiagnosticsError = 'red'
LspDiagnosticsWarning = 'yellow'
LspDiagnosticsInformation = 'cyan'
LspDiagnosticsInfo = 'cyan'
LspDiagnosticsHint = 'cyan'
LspDiagnosticsUnderlineError = '- - u red'
LspDiagnosticsUnderlineWarning = '- - u yellow'
LspDiagnosticsUnderlineInformation = '- - u cyan'
LspDiagnosticsUnderlineInfo = '- - u cyan'
LspDiagnosticsUnderlineHint = '- - u cyan'
LspReferenceRead = 'orange'
LspReferenceText = 'orange'
LspReferenceWrite = 'orange'
LspCodeLens = 'context - i'
LspCodeLensSeparator = 'context - i'

[Telescope]
TelescopeSelection = 'white selection'
TelescopeMultiSelection = 'purple selection'
TelescopeNormal = 'fg bg'
TelescopeMatching = 'green'
TelescopeBorder = 'comment'
TelescopePromptPrefix = 'purple'

[NvimTree]
NvimTreeFolderIcon = 'purple'
NvimTreeIndentMarker = 'white'
NvimTreeNormal = 'white bg_dark'
NvimTreeNormalNC = 'link:NvimTreeNormal'
NvimTreeVertSplit = 'bg_dark bg'
NvimTreeFolderName = 'fg'
NvimTreeOpenedFolderName = 'fg - bi'
NvimTreeEmptyFolderName = 'comment - i'
NvimTreeGitIgnored = 'white - i'
NvimTreeImageFile = 'pink'
NvimTreeSpecialFile = 'pink'
NvimTreeEndOfBuffer = 'white'
NvimTreeCursorLine = '- selection'
NvimTreeGitignoreIcon = 'orange'
NvimTreeGitStaged = 'cyan'
NvimTreeGitNew = 'bright_green'
NvimTreeGitRenamed = 'green'
NvimTreeGitDeleted = 'red'
NvimTreeGitMerge = 'cyan'
NvimTreeGitDirty = 'yellow'

NvimTreeSymlink = 'orange'
NvimTreeRootFolder = 'fg - b'
NvimTreeExecFile = 'bright_green'

[Buffer]
BufferCurrent = 'fg bg'
BufferCurrentIndex = 'fg bg'
BufferCurrentMod = 'yellow bg'
BufferCurrentSign = 'bright_cyan bg'
BufferCurrentTarget = 'red bg b'

BufferVisible = 'fg bg'
BufferVisibleIndex = 'fg bg'
BufferVisibleMod = 'yellow bg'
BufferVisibleSign = 'white bg'
BufferVisibleTarget = 'red bg b'

BufferInactive = 'white black'
BufferInactiveIndex = 'white black'
BufferInactiveMod = 'yellow black'
BufferInactiveSign = 'white black'
BufferInactiveTarget = 'red black b'

[StatusLine]
StatusLine = 'white bg_dark'
StatusLineNC = 'comment -'
StatusLineSeparator = 'bg_dark'
StatusLineTerm = 'white black'
StatusLineTermNC = 'comment'

[IndentBlankline]
IndentBlanklineContextChar = 'context'
IndentBlanklineContextStart = '- - u'
IndentBlanklineChar = 'white'
IndentBlanklineSpaceChar = 'cyan'
IndentBlanklineSpaceCharBlankline = 'yellow'

[Dashboard]
DashboardHeader = 'purple'
DashboardCenter = 'pink'
DashboardFooter = 'purple'

[Cmp]
CmpItemAbbrDeprecated = 'white menu s'
CmpItemAbbrMatch = 'cyan menu'
CmpItemAbbrMatchFuzzy = 'cyan menu'
CmpItemKindFunction = 'link:TSFunction'
CmpItemKindMethod = 'link:TSMethod'
CmpItemKindConstructor = 'link:TSConstructor'
CmpItemKindClass = 'link:TSType'
CmpItemKindEnum = 'link:TSField'
CmpItemKindEvent = 'link:TSConstant'
CmpItemKindInterface = 'link:TSType'
CmpItemKindStruct = 'link:TSStructure'
CmpItemKindVariable = 'link:TSVariable'
CmpItemKindField = 'link:TSField'
CmpItemKindProperty = 'link:TSProperty'
CmpItemKindEnumMember = 'link:TSField'
CmpItemKindConstant = 'link:TSConstant'
CmpItemKindKeyword = 'link:TSKeyword'
CmpItemKindModule = 'link:TSNamespace'
CmpItemKindValue = 'link:TSField'
CmpItemKindUnit = 'link:TSField'
CmpItemKindText = 'link:TSText'
CmpItemKindSnippet = 'link:TSText'
CmpItemKindFile = 'link:TSURI'
CmpItemKindFolder = 'link:TSURI'
CmpItemKindColor = 'fg'
CmpItemKindReference = 'link:TSParameterReference'
CmpItemKindOperator = 'link:TSOperator'
CmpItemKindTypeParameter = 'link:TSParameter'

[Notify]
NotifyERRORBorder = 'red'
NotifyWARNBorder = 'yellow'
NotifyINFOBorder =  'cyan'
NotifyDEBUGBorder = 'red'
NotifyTRACEBorder = 'white'
NotifyERRORIcon = 'red'
NotifyWARNIcon = 'yellow'
NotifyINFOIcon = 'cyan'
NotifyDEBUGIcon = 'white'
NotifyTRACEIcon = 'white'
NotifyERRORTitle = 'red'
NotifyWARNTitle = 'yellow'
NotifyINFOTitle = 'cyan'
NotifyDEBUGTitle = 'white'
NotifyTRACETitle = 'white'
NotifyERRORBody = 'link:Normal'
NotifyWARNBody = 'link:Normal'
NotifyINFOBody = 'link:Normal'
NotifyDEBUGBody = 'link:Normal'
NotifyTRACEBody = 'link:Normal'
